CREATE TABLE identity (
       identityid serial PRIMARY KEY,
       userid integer NOT NULL REFERENCES quasseluser (userid) ON DELETE CASCADE,
       identityname varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
       realname varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
       awaynick varchar(64) CHARACTER SET utf8 COLLATE utf8_bin,
       awaynickenabled boolean NOT NULL DEFAULT FALSE,
       awayreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       awayreasonenabled boolean NOT NULL DEFAULT FALSE,
       autoawayenabled boolean NOT NULL DEFAULT FALSE,
       autoawaytime integer NOT NULL,
       autoawayreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       autoawayreasonenabled boolean NOT NULL DEFAULT FALSE,
       detachawayenabled boolean NOT NULL DEFAULT FALSE,
       detachawayreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       detachawayreasonenabled boolean NOT NULL DEFAULT FALSE,
       ident varchar(64) CHARACTER SET utf8 COLLATE utf8_bin,
       kickreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       partreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       quitreason varchar(256) CHARACTER SET utf8 COLLATE utf8_bin,
       sslcert BLOB,
       sslkey BLOB,
       UNIQUE (userid, identityname)
)
